# Use NFC pads as GPIOS
CONFIG_NFCT_PINS_AS_GPIOS=y

# Enable deep sleep
CONFIG_ZMK_SLEEP=y

# Disable ZMK Studio (can cause flashing issues on macOS)
# CONFIG_ZMK_STUDIO=y

# Enable Layer Status Widget
CONFIG_ZMK_WIDGET_LAYER_STATUS=y

# Enable Output Status (USB/Bluetooth) Widget
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# Enable Words Per Minute (WPM) Widget
CONFIG_ZMK_WIDGET_WPM_STATUS=y
